#term = "alacritty"

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[cursor]
style = "Beam"
unfocused_hollow = false

[font]
size = 12

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 1

[window.padding]
#decorations = "none"
#dynamic_padding = true
x = 25
y = 25
